name: edriving_spim_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5 
  flutter_screenutil: ^5.6.0 
  hive: ^2.2.3 
  xml2json: ^5.3.2 
  html_unescape: ^2.0.0 
  intl: ^0.17.0 
  flutter_geocoder: ^0.2.2-nullsafety 
  geolocator: ^9.0.2 
  http: ^0.13.5 
  another_flushbar: ^1.12.29 
  device_info: ^2.0.3 
  photo_view: ^0.13.0 
  auto_route: ^5.0.4 
  provider: ^6.0.5 
  flutter_spinkit: ^5.1.0 
  shared_preferences: ^2.0.15 
  rxdart: ^0.27.7 
  flutter_typeahead: ^4.1.1 
  shimmer: ^2.0.0 
  transparent_image: ^2.0.0 
  flutter_widget_from_html: ^0.9.0+2 
  flutter_custom_clippers: ^2.1.0 
  map_launcher: ^2.4.0 
  app_settings: ^4.1.8 
  camera: ^0.10.1 
  datetime_picker_formfield: ^2.0.1 
  image_picker: ^0.8.6 
  image_cropper: ^3.0.1 
  qr_flutter: ^4.0.0 
  readmore: ^2.2.0 
  string_validator: ^0.3.0 
  package_info: ^2.0.2 
  badges: ^3.0.2
  qr_code_scanner: ^1.0.1 
  flutter_linkify: ^5.0.2 
  country_code_picker: ^2.0.2 
  random_color: ^1.0.6-nullsafety 
  supercharged: ^2.1.1 
  printing: ^5.6.5 

  flutter_share: ^2.0.0 
  pdfx: ^1.0.1+1
  share: ^2.0.4 
  flutter_rating_bar: ^4.0.1
  google_fonts: ^3.0.1
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.0.0+2
  flutter_localizations:
    sdk: flutter
  native_pdf_view: ^6.0.0+1

  #chat
  file_picker: ^4.6.1
  flutter_easyloading: ^3.0.5
  permission_handler: ^10.2.0
  socket_io_client: ^2.0.1
  sqflite: ^2.2.4+1
  uuid: ^3.0.7
  get: ^4.6.5
  flick_video_player: ^0.5.0
  visibility_detector: ^0.4.0+2
  video_player: ^2.5.1
  flutter_sound: ^9.2.13
  open_file: ^3.2.1
  audio_session: ^0.1.13
  bubble: ^1.2.1
  full_screen_image_null_safe: ^2.0.0
  flutter_local_notifications: ^12.0.4
  firebase_core: ^2.5.0
  firebase_messaging: ^14.2.2
  jumping_dot: ^0.0.4
  scrollable_positioned_list: ^0.3.5
  flutter_slidable: ^2.0.0
  emoji_picker_flutter: ^1.5.2
  flutter_sound_platform_interface: ^9.2.13
  swipe_to: ^1.0.2
  date_time_picker: ^2.1.0
  lottie: ^2.2.0
  record: ^4.4.4
  flutter_vibrate: ^1.3.0
  font_awesome_flutter: ^10.4.0
  just_audio: ^0.9.31
  google_maps_flutter: ^2.2.3
  dotted_border: ^2.0.0+1
  flutter_emoji: ">= 2.0.0"
  connectivity_plus: ^3.0.4
  csslib: 0.17.0
  
dependency_overrides:
  modal_bottom_sheet:
    git:
      url: https://github.com/danReynolds/modal_bottom_sheet.git
      path: modal_bottom_sheet

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.1 

flutter_icons:
  android: true
  ios: true
  image_path_android: 'assets/icon/android-icon.png'
  image_path_ios: 'assets/icon/ios-icon.png'

flutter_native_splash:
  image: assets/splash/splash.png
  color: "ffcd0e"
  android_disable_fullscreen: true

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/lang/en.json
    - assets/lang/ms.json

  fonts:
    - family: Myriad
      fonts:
        - asset: assets/fonts/MYRIADPRO-REGULAR.otf
        - asset: assets/fonts/MYRIADPRO-BOLD.otf
          weight: 700

    - family: MyCustomIcons
      fonts:
        - asset: assets/fonts/MyCustomIcons.ttf
 
